export const ERROR_CODES = {
  REIP_BAJO_UMBRAL: 'REIP_BAJO_UMBRAL',
  ERROR_RUT_INVALIDO: 'ERROR_RUT_INVALIDO',
  ERROR_FECHA_INVALIDA: 'ERROR_FECHA_INVALIDA',
  ERROR_SBP_INSUFICIENTE: 'ERROR_SBP_INSUFICIENTE',
  ERROR_MONTO_INVALIDO: 'ERROR_MONTO_INVALIDO',
  ERROR_REIP_INVALIDO: 'ERROR_REIP_INVALIDO',
  ERROR_CAMPO_FALTANTE: 'ERROR_CAMPO_FALTANTE',
  ERROR_TIPO_INVALIDO: 'ERROR_TIPO_INVALIDO',
  ERROR_TEMPORALIDAD: 'ERROR_TEMPORALIDAD',
  ERROR_MARCO_NORMATIVO: 'ERROR_MARCO_NORMATIVO',
  ERROR_PRERREQUISITO: 'ERROR_PRERREQUISITO',
  RECHAZADO: 'RECHAZADO',
  RECHAZADO_COBERTURA: 'RECHAZADO_COBERTURA',
  RECHAZADO_DUPLICADO: 'RECHAZADO_DUPLICADO',
  RECHAZADO_PRESCRIPCION: 'RECHAZADO_PRESCRIPCION',
  PENDIENTE_ACUMULACION: 'PENDIENTE_ACUMULACION',
  DEUDA_TRABAJADOR: 'DEUDA_TRABAJADOR',
  EXCESO_PAGO: 'EXCESO_PAGO',
  CONSUMIDO: 'CONSUMIDO',
  SOBREVIVENCIA_SIN_BENEFICIARIOS: 'SOBREVIVENCIA_SIN_BENEFICIARIOS',
  EXD_PAG_030: 'EXD-PAG-030',
  EXD_SBM_001: 'EXD-SBM-001',
  EXD_SBM_006: 'EXD-SBM-006',
  MONTO_MINIMO: 'MONTO_MINIMO',
  IMNR_PISO_APLICADO: 'IMNR_PISO_APLICADO',
  ACEPTADO: 'ACEPTADO',
  ACEPTADO_NORMALIZADO: 'ACEPTADO_NORMALIZADO',
  SIN_CAMBIO: 'SIN_CAMBIO',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export class PpeeError extends Error {
  readonly code: ErrorCode;
  readonly conformidades: string[];

  constructor(code: ErrorCode, message: string, conformidades: string[] = []) {
    super(message);
    this.name = 'PpeeError';
    this.code = code;
    this.conformidades = conformidades;
  }
}

export function isPpeeError(value: unknown): value is PpeeError {
  return value instanceof PpeeError;
}
